### ISSUE TITLE
[Risk: Informational] inaccurate GAS calculation

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#13]
On NEO platform, contract can get the remaining available GAS for code execution by `Runtime.GasLeft`. Contract could also get the total GAS consumed by a transaction by `tx.SystemFee` and `tx.NetworkFee`.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.cs#L130-L132

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.cs#L156-L162

If the admin call `CancelInfusion` for multiple users in one transaction, the GAS will be miscalculated and counted multiple times. If not, the admin will have to afford the NetworkFee and a few SystemFee before this function's execution.

Therefore, it's recommended to use the `((Transaction)Runtime.ScriptContainer).SystemFee + ((Transaction)Runtime.ScriptContainer).NetworkFee` and make sure only perform `CancelInfusion` for one user at once.

**Comment by RawichK** [comment]
This means that when an admin invokes `CancelInfusion` as a batch by bundling multiple scripts for multiple users into 1 transaction, each method invocation will use the same `tx.SystemFee` and `tx.NetworkFee` value. So, the `refundGas` will be less than only one invocation for one user.

@digimbyte I would like to confirm with you that we can do this approach programmatically, so building one script for one user and submitting each tx to the chain one by one is not time-consuming.

**Comment by digimbyte** [comment]
Approved to implement.
