### ISSUE TITLE
[Risk: High] insufficient permission verification

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#4]
On NEO platform, it's usually recommended to verify one address's permission by [`Runtime.CheckWitness`](https://github.com/neo-project/neo/blob/629baf819f9ebedec4b2e89e7b55a5adf1836597/src/Neo/SmartContract/ApplicationEngine.Runtime.cs#L105) and users can control their permissions in details by different [WitnessRules](https://github.com/neo-project/neo/blob/master/src/Neo/Network/P2P/Payloads/WitnessRule.cs) and [WitnessScopes](https://github.com/neo-project/neo/blob/master/src/Neo/Network/P2P/Payloads/WitnessScope.cs).

In hardened project, the `owner`'s permission is well checked by both `Runtime.CheckWitness` and the transaction's sender [here](https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Owner.cs#L14). While in contrast, the `admin`'s permission is only checked by the `tx.Sender`. Noticed that on NEO blockchain, the `tx.Sender`'s concept is somehow like the `tx.origin` on EVM-chains. We should not verify one's permission willing by only checking this sender cause any malicious dAPP could redirect a tx's execution path to anywhere.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L18-L31

It's recommended to replace the  second `return true` to `return Runtime.CheckwWtness(tx.Sender)`.

**Comment by RawichK** [comment]
This is a bug that will be fixed and can be closed.
