### ISSUE TITLE
[Risk: High] reentrancy risk

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#5]
There is a widely used pattern for resisting reentrancy attack called [Checks-Effects-Interactions Pattern](https://docs.soliditylang.org/en/v0.6.11/security-considerations.html).

In hardened project, the `InfusionMint` and `InfusionUpdate` as well as `CancelInfusion` didn't follow this pattern. Among all these functions, conditions are checked first, then the `Safe11Transfer` and `Safe17Transfer` and sometimes `Mint` are called, while the contract's storage is changed at the last step. All those token transfer could call unknown external code and may re-enter the hardened's contract. The attacker could drain the contract's NEP-17 token by re-enter the `CancelInfusion`. Combined with the https://github.com/battlehard/hardened/issues/4 issue, the other two could also introduce damages to the contract.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L73
https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L120
https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.cs#L130

It's recommended to change the `PendingStorage`'s state before all those external calls. The functions could perform checks first as before, and then change the `PendingStorage`, and at the last step do all other interactions such as transfer NEP-11 and NEP-17 to other addresses.

Although `Unfuse` and `BurnInfusion` won't cause damages by reentrancy attack. It's also recommended to `ReturnLockNFTs` after `UpdateState` or `Burn`. Always trying to make the external interaction in these functions at the last step is a good practice.

**Comment by RawichK** [comment]
Got your point, @overlordsecurity what is your opinion about adding this line as the first line in those methods?
`Assert(Runtime.InvocationCounter == 1, "Re-Entrancy Not Allowed");`

I recalled that this was also another solution for preventing reentrancy. If this line can be used, I think it will be more explicit and straightforward than changing contract storage before calling external methods. Of course, in this project, I will also make sure that the storage must be updated before calling external methods to adhere to the best practice.

**Comment by overlordsecurity** [comment]
Yeah. [Checks-Effects-Interactions Pattern](https://docs.soliditylang.org/en/v0.6.11/security-considerations.html) is already good for most of the sences. Of cause you can use this one for Re-Entrancy resistance. While this is hard to use when you combine the function with other functions or call it multiple times in one transaction.

A good practice is actually keeping this for assuring no Re-Entrancy issue would happen. To do so, you should keep the reusable part in a private function and make sure that no public function would call any other public functions. Then add this check for every public function.

**Comment by RawichK** [comment]
@digimbyte this case is being fixing and can close.
