### ISSUE TITLE
[Risk: Medium] potential key conflicts

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#6]
In NEO's devpacks, the `Nep11Token` contract template already take use of the prefixes from 0x00 to 0x04 [here](https://github.com/neo-project/neo-devpack-dotnet/blob/e3340740306252841cbdbc6c411ed2559d2037ff/src/Neo.SmartContract.Framework/TokenContract.cs#L20-L21) and [here](https://github.com/neo-project/neo-devpack-dotnet/blob/e3340740306252841cbdbc6c411ed2559d2037ff/src/Neo.SmartContract.Framework/Nep11Token.cs#L30-L32).

In hardened, we still using the prefix 0x01 and 0x02 for other purposes. If the keys concatenated after the prefix were not well checked, the real storage key could conflict with the internal `Nep11Token`'s keys.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Storage.cs#L13-L19

It's recommended to change the first prefix starting from 0x05 or 0x10.

**Comment by digimbyte** [comment]
Lets move to 0x10 to keep things simple and clean
