### ISSUE TITLE
[Risk: Low] non-compliance with the NEP-11 proposal

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#7]
In NEO's proposal NEP-11, the standard method for getting a NFT's owner is the [`ownerOf`](https://github.com/neo-project/proposals/blob/master/nep-11.mediawiki#user-content-ownerOf) method. And the `properties`'s fields are not strictly constrained in the standard.

In hardened project, `ValidateExternalNftOwnership` function use the `properties` instead of `ownerOf` for getting a NFT's owner which didn't conform to the proposal.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Helpers.cs#L20

It's recommended to call the `ownerOf` method instead as suggested by the proposal here.

**Comment by RawichK** [comment]
@digimbyte This case is being fix and can be closed.
